// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // operatore
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class OperatoreConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Operatore>
    {
        public OperatoreConfiguration()
            : this("dbo")
        {
        }

        public OperatoreConfiguration(string schema)
        {
            ToTable("operatore", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Nome).HasColumnName(@"nome").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Cognome).HasColumnName(@"cognome").HasColumnType("nvarchar").IsRequired().HasMaxLength(1000);
            Property(x => x.Username).HasColumnName(@"username").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Password).HasColumnName(@"password").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.IdCreatedbyuser).HasColumnName(@"id_createdbyuser").HasColumnType("int").IsOptional();
            Property(x => x.Createdon).HasColumnName(@"createdon").HasColumnType("datetime").IsRequired();
            Property(x => x.IdLastupdatesbyuser).HasColumnName(@"id_lastupdatesbyuser").HasColumnType("int").IsRequired();
            Property(x => x.Lastupdateon).HasColumnName(@"lastupdateon").HasColumnType("datetime").IsRequired();
            Property(x => x.Isactive).HasColumnName(@"isactive").HasColumnType("int").IsRequired();

            // Foreign keys
            HasOptional(a => a.Operatore_IdCreatedbyuser).WithMany(b => b.Operatori_IdCreatedbyuser).HasForeignKey(c => c.IdCreatedbyuser).WillCascadeOnDelete(false); // FK_operatore_operatore_creaz
            HasRequired(a => a.Operatore_IdLastupdatesbyuser).WithMany(b => b.Operatori_IdLastupdatesbyuser).HasForeignKey(c => c.IdLastupdatesbyuser).WillCascadeOnDelete(false); // FK_operatore_operatore_update
        }
    }

}
// </auto-generated>
