// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // operatore
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class Operatore
    {
        public int Id { get; set; } // id (Primary key)
        public string Nome { get; set; } // nome (length: 100)
        public string Cognome { get; set; } // cognome (length: 1000)
        public string Username { get; set; } // username (length: 100)
        public string Password { get; set; } // password (length: 100)
        public int? IdCreatedbyuser { get; set; } // id_createdbyuser
        public System.DateTime Createdon { get; set; } // createdon
        public int IdLastupdatesbyuser { get; set; } // id_lastupdatesbyuser
        public System.DateTime Lastupdateon { get; set; } // lastupdateon
        public int Isactive { get; set; } // isactive

        // Reverse navigation

        /// <summary>
        /// Child Operatori where [operatore].[id_createdbyuser] point to this entity (FK_operatore_operatore_creaz)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Operatore> Operatori_IdCreatedbyuser { get; set; } // operatore.FK_operatore_operatore_creaz
        /// <summary>
        /// Child Operatori where [operatore].[id_lastupdatesbyuser] point to this entity (FK_operatore_operatore_update)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Operatore> Operatori_IdLastupdatesbyuser { get; set; } // operatore.FK_operatore_operatore_update

        // Foreign keys

        /// <summary>
        /// Parent Operatore pointed by [operatore].([IdCreatedbyuser]) (FK_operatore_operatore_creaz)
        /// </summary>
        public virtual Operatore Operatore_IdCreatedbyuser { get; set; } // FK_operatore_operatore_creaz

        /// <summary>
        /// Parent Operatore pointed by [operatore].([IdLastupdatesbyuser]) (FK_operatore_operatore_update)
        /// </summary>
        public virtual Operatore Operatore_IdLastupdatesbyuser { get; set; } // FK_operatore_operatore_update

        public Operatore()
        {
            Operatori_IdCreatedbyuser = new System.Collections.Generic.List<Operatore>();
            Operatori_IdLastupdatesbyuser = new System.Collections.Generic.List<Operatore>();
        }
    }

}
// </auto-generated>
