// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_ORDERS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoOrderConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DemoOrder>
    {
        public DemoOrderConfiguration()
            : this("SOMMINISTRAZIONE")
        {
        }

        public DemoOrderConfiguration(string schema)
        {
            ToTable("DEMO_ORDERS", schema);
            HasKey(x => x.OrderId);

            Property(x => x.OrderId).HasColumnName(@"ORDER_ID").HasColumnType("number").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CustomerId).HasColumnName(@"CUSTOMER_ID").HasColumnType("number").IsRequired();
            Property(x => x.OrderTotal).HasColumnName(@"ORDER_TOTAL").HasColumnType("number").IsOptional().HasPrecision(8,2);
            Property(x => x.OrderTimestamp).HasColumnName(@"ORDER_TIMESTAMP").HasColumnType("date").IsOptional();
            Property(x => x.UserId).HasColumnName(@"USER_ID").HasColumnType("number").IsOptional();

            // Foreign keys
            HasOptional(a => a.DemoUser).WithMany(b => b.DemoOrders).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // DEMO_ORDERS_USER_ID_FK
            HasRequired(a => a.DemoCustomer).WithMany(b => b.DemoOrders).HasForeignKey(c => c.CustomerId).WillCascadeOnDelete(false); // DEMO_ORDERS_CUSTOMER_ID_FK
        }
    }

}
// </auto-generated>
