// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_PRODUCT_INFO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoProductInfoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DemoProductInfo>
    {
        public DemoProductInfoConfiguration()
            : this("SOMMINISTRAZIONE")
        {
        }

        public DemoProductInfoConfiguration(string schema)
        {
            ToTable("DEMO_PRODUCT_INFO", schema);
            HasKey(x => x.ProductId);

            Property(x => x.ProductId).HasColumnName(@"PRODUCT_ID").HasColumnType("number").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProductName).HasColumnName(@"PRODUCT_NAME").HasColumnType("varchar2").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ProductDescription).HasColumnName(@"PRODUCT_DESCRIPTION").HasColumnType("varchar2").IsOptional().IsUnicode(false).HasMaxLength(2000);
            Property(x => x.Category).HasColumnName(@"CATEGORY").HasColumnType("varchar2").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.ProductAvail).HasColumnName(@"PRODUCT_AVAIL").HasColumnType("varchar2").IsOptional().IsUnicode(false).HasMaxLength(1);
            Property(x => x.ListPrice).HasColumnName(@"LIST_PRICE").HasColumnType("number").IsOptional().HasPrecision(8,2);
            Property(x => x.ProductImage).HasColumnName(@"PRODUCT_IMAGE").HasColumnType("blob").IsOptional();
            Property(x => x.Mimetype).HasColumnName(@"MIMETYPE").HasColumnType("varchar2").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Filename).HasColumnName(@"FILENAME").HasColumnType("varchar2").IsOptional().IsUnicode(false).HasMaxLength(400);
            Property(x => x.ImageLastUpdate).HasColumnName(@"IMAGE_LAST_UPDATE").HasColumnType("date").IsOptional();
        }
    }

}
// </auto-generated>
