// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_ORDER_ITEMS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoOrderItemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DemoOrderItem>
    {
        public DemoOrderItemConfiguration()
            : this("SOMMINISTRAZIONE")
        {
        }

        public DemoOrderItemConfiguration(string schema)
        {
            ToTable("DEMO_ORDER_ITEMS", schema);
            HasKey(x => x.OrderItemId);

            Property(x => x.OrderItemId).HasColumnName(@"ORDER_ITEM_ID").HasColumnType("number").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.OrderId).HasColumnName(@"ORDER_ID").HasColumnType("number").IsRequired();
            Property(x => x.ProductId).HasColumnName(@"PRODUCT_ID").HasColumnType("number").IsRequired();
            Property(x => x.UnitPrice).HasColumnName(@"UNIT_PRICE").HasColumnType("number").IsRequired().HasPrecision(8,2);
            Property(x => x.Quantity).HasColumnName(@"QUANTITY").HasColumnType("number").IsRequired();

            // Foreign keys
            HasRequired(a => a.DemoOrder).WithMany(b => b.DemoOrderItems).HasForeignKey(c => c.OrderId); // DEMO_ORDER_ITEMS_FK
            HasRequired(a => a.DemoProductInfo).WithMany(b => b.DemoOrderItems).HasForeignKey(c => c.ProductId); // DEMO_ORDER_ITEMS_PRODUCT_ID_FK
        }
    }

}
// </auto-generated>
