// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // The table 'DEMO_STATES' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // DEMO_STATES
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoState
    {
        public string St { get; set; } // ST (length: 30)
        public string StateName { get; set; } // STATE_NAME (length: 30)
    }

}
// </auto-generated>
