// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_CUSTOMERS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoCustomer
    {
        public decimal CustomerId { get; set; } // CUSTOMER_ID (Primary key)
        public string CustFirstName { get; set; } // CUST_FIRST_NAME (length: 20)
        public string CustLastName { get; set; } // CUST_LAST_NAME (length: 20)
        public string CustStreetAddress1 { get; set; } // CUST_STREET_ADDRESS1 (length: 60)
        public string CustStreetAddress2 { get; set; } // CUST_STREET_ADDRESS2 (length: 60)
        public string CustCity { get; set; } // CUST_CITY (length: 30)
        public string CustState { get; set; } // CUST_STATE (length: 2)
        public string CustPostalCode { get; set; } // CUST_POSTAL_CODE (length: 10)
        public string PhoneNumber1 { get; set; } // PHONE_NUMBER1 (length: 25)
        public string PhoneNumber2 { get; set; } // PHONE_NUMBER2 (length: 25)
        public decimal? CreditLimit { get; set; } // CREDIT_LIMIT
        public string CustEmail { get; set; } // CUST_EMAIL (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child DemoOrders where [DEMO_ORDERS].[CUSTOMER_ID] point to this entity (DEMO_ORDERS_CUSTOMER_ID_FK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DemoOrder> DemoOrders { get; set; } // DEMO_ORDERS.DEMO_ORDERS_CUSTOMER_ID_FK

        public DemoCustomer()
        {
            DemoOrders = new System.Collections.Generic.List<DemoOrder>();
        }
    }

}
// </auto-generated>
