// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_USERS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoUserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DemoUser>
    {
        public DemoUserConfiguration()
            : this("SOMMINISTRAZIONE")
        {
        }

        public DemoUserConfiguration(string schema)
        {
            ToTable("DEMO_USERS", schema);
            HasKey(x => x.UserId);

            Property(x => x.UserId).HasColumnName(@"USER_ID").HasColumnType("number").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UserName).HasColumnName(@"USER_NAME").HasColumnType("varchar2").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Password).HasColumnName(@"PASSWORD").HasColumnType("varchar2").IsOptional().IsUnicode(false).HasMaxLength(4000);
            Property(x => x.CreatedOn).HasColumnName(@"CREATED_ON").HasColumnType("date").IsOptional();
            Property(x => x.Quota).HasColumnName(@"QUOTA").HasColumnType("number").IsOptional();
            Property(x => x.Products).HasColumnName(@"PRODUCTS").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            Property(x => x.ExpiresOn).HasColumnName(@"EXPIRES_ON").HasColumnType("date").IsOptional();
            Property(x => x.AdminUser).HasColumnName(@"ADMIN_USER").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
