// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_PRODUCT_INFO
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoProductInfo
    {
        public decimal ProductId { get; set; } // PRODUCT_ID (Primary key)
        public string ProductName { get; set; } // PRODUCT_NAME (length: 50)
        public string ProductDescription { get; set; } // PRODUCT_DESCRIPTION (length: 2000)
        public string Category { get; set; } // CATEGORY (length: 30)
        public string ProductAvail { get; set; } // PRODUCT_AVAIL (length: 1)
        public decimal? ListPrice { get; set; } // LIST_PRICE
        public byte[] ProductImage { get; set; } // PRODUCT_IMAGE
        public string Mimetype { get; set; } // MIMETYPE (length: 255)
        public string Filename { get; set; } // FILENAME (length: 400)
        public System.DateTime? ImageLastUpdate { get; set; } // IMAGE_LAST_UPDATE

        // Reverse navigation

        /// <summary>
        /// Child DemoOrderItems where [DEMO_ORDER_ITEMS].[PRODUCT_ID] point to this entity (DEMO_ORDER_ITEMS_PRODUCT_ID_FK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DemoOrderItem> DemoOrderItems { get; set; } // DEMO_ORDER_ITEMS.DEMO_ORDER_ITEMS_PRODUCT_ID_FK

        public DemoProductInfo()
        {
            DemoOrderItems = new System.Collections.Generic.List<DemoOrderItem>();
        }
    }

}
// </auto-generated>
