// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_USERS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoUser
    {
        public decimal UserId { get; set; } // USER_ID (Primary key)
        public string UserName { get; set; } // USER_NAME (length: 100)
        public string Password { get; set; } // PASSWORD (length: 4000)
        public System.DateTime? CreatedOn { get; set; } // CREATED_ON
        public decimal? Quota { get; set; } // QUOTA
        public string Products { get; set; } // PRODUCTS (length: 1)
        public System.DateTime? ExpiresOn { get; set; } // EXPIRES_ON
        public string AdminUser { get; set; } // ADMIN_USER (length: 1)

        // Reverse navigation

        /// <summary>
        /// Child DemoOrders where [DEMO_ORDERS].[USER_ID] point to this entity (DEMO_ORDERS_USER_ID_FK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DemoOrder> DemoOrders { get; set; } // DEMO_ORDERS.DEMO_ORDERS_USER_ID_FK

        public DemoUser()
        {
            DemoOrders = new System.Collections.Generic.List<DemoOrder>();
        }
    }

}
// </auto-generated>
