// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_ORDERS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoOrder
    {
        public decimal OrderId { get; set; } // ORDER_ID (Primary key)
        public decimal CustomerId { get; set; } // CUSTOMER_ID
        public decimal? OrderTotal { get; set; } // ORDER_TOTAL
        public System.DateTime? OrderTimestamp { get; set; } // ORDER_TIMESTAMP
        public decimal? UserId { get; set; } // USER_ID

        // Reverse navigation

        /// <summary>
        /// Child DemoOrderItems where [DEMO_ORDER_ITEMS].[ORDER_ID] point to this entity (DEMO_ORDER_ITEMS_FK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DemoOrderItem> DemoOrderItems { get; set; } // DEMO_ORDER_ITEMS.DEMO_ORDER_ITEMS_FK

        // Foreign keys

        /// <summary>
        /// Parent DemoCustomer pointed by [DEMO_ORDERS].([CustomerId]) (DEMO_ORDERS_CUSTOMER_ID_FK)
        /// </summary>
        public virtual DemoCustomer DemoCustomer { get; set; } // DEMO_ORDERS_CUSTOMER_ID_FK

        /// <summary>
        /// Parent DemoUser pointed by [DEMO_ORDERS].([UserId]) (DEMO_ORDERS_USER_ID_FK)
        /// </summary>
        public virtual DemoUser DemoUser { get; set; } // DEMO_ORDERS_USER_ID_FK

        public DemoOrder()
        {
            DemoOrderItems = new System.Collections.Generic.List<DemoOrderItem>();
        }
    }

}
// </auto-generated>
