// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // DEMO_ORDER_ITEMS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class DemoOrderItem
    {
        public short OrderItemId { get; set; } // ORDER_ITEM_ID (Primary key)
        public decimal OrderId { get; set; } // ORDER_ID
        public decimal ProductId { get; set; } // PRODUCT_ID
        public decimal UnitPrice { get; set; } // UNIT_PRICE
        public int Quantity { get; set; } // QUANTITY

        // Foreign keys

        /// <summary>
        /// Parent DemoOrder pointed by [DEMO_ORDER_ITEMS].([OrderId]) (DEMO_ORDER_ITEMS_FK)
        /// </summary>
        public virtual DemoOrder DemoOrder { get; set; } // DEMO_ORDER_ITEMS_FK

        /// <summary>
        /// Parent DemoProductInfo pointed by [DEMO_ORDER_ITEMS].([ProductId]) (DEMO_ORDER_ITEMS_PRODUCT_ID_FK)
        /// </summary>
        public virtual DemoProductInfo DemoProductInfo { get; set; } // DEMO_ORDER_ITEMS_PRODUCT_ID_FK
    }

}
// </auto-generated>
