// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    public interface ISomministrazioneDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<DemoCustomer> DemoCustomers { get; set; } // DEMO_CUSTOMERS
        System.Data.Entity.DbSet<DemoOrder> DemoOrders { get; set; } // DEMO_ORDERS
        System.Data.Entity.DbSet<DemoOrderItem> DemoOrderItems { get; set; } // DEMO_ORDER_ITEMS
        System.Data.Entity.DbSet<DemoProductInfo> DemoProductInfoes { get; set; } // DEMO_PRODUCT_INFO
        System.Data.Entity.DbSet<DemoUser> DemoUsers { get; set; } // DEMO_USERS
        System.Data.Entity.DbSet<Operatore> Operatori { get; set; } // OPERATORE

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
