// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // OPERATORE
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Operatore
    {
        public long Id { get; set; } // ID (Primary key)
        public string Nome { get; set; } // NOME (length: 100)
        public string Cognome { get; set; } // COGNOME (length: 100)
        public string Username { get; set; } // USERNAME (length: 100)
        public string Password { get; set; } // PASSWORD (length: 100)
        public long? IdCreatedbyuser { get; set; } // ID_CREATEDBYUSER
        public System.DateTime Createdon { get; set; } // CREATEDON
        public long? IdLastupdatedbyuser { get; set; } // ID_LASTUPDATEDBYUSER
        public System.DateTime Lastupdatedon { get; set; } // LASTUPDATEDON
        public long Isactive { get; set; } // ISACTIVE
    }

}
// </auto-generated>
