// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{

    // OPERATORE
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class OperatoreConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Operatore>
    {
        public OperatoreConfiguration()
            : this("SOMMINISTRAZIONE")
        {
        }

        public OperatoreConfiguration(string schema)
        {
            ToTable("OPERATORE", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("number").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Nome).HasColumnName(@"NOME").HasColumnType("varchar2").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Cognome).HasColumnName(@"COGNOME").HasColumnType("varchar2").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Username).HasColumnName(@"USERNAME").HasColumnType("varchar2").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Password).HasColumnName(@"PASSWORD").HasColumnType("varchar2").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.IdCreatedbyuser).HasColumnName(@"ID_CREATEDBYUSER").HasColumnType("number").IsOptional();
            Property(x => x.Createdon).HasColumnName(@"CREATEDON").HasColumnType("date").IsRequired();
            Property(x => x.IdLastupdatedbyuser).HasColumnName(@"ID_LASTUPDATEDBYUSER").HasColumnType("number").IsOptional();
            Property(x => x.Lastupdatedon).HasColumnName(@"LASTUPDATEDON").HasColumnType("date").IsRequired();
            Property(x => x.Isactive).HasColumnName(@"ISACTIVE").HasColumnType("number").IsRequired();
        }
    }

}
// </auto-generated>
