// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Somministrazioni.Data.Models.DBEntities
{
    using EntityFramework.DbContextScope.Interfaces;
    using Oracle.ManagedDataAccess.Client;
    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SomministrazioneDbContext : System.Data.Entity.DbContext, ISomministrazioneDbContext, IDbContext
    {
        public System.Data.Entity.DbSet<DemoCustomer> DemoCustomers { get; set; } // DEMO_CUSTOMERS
        public System.Data.Entity.DbSet<DemoOrder> DemoOrders { get; set; } // DEMO_ORDERS
        public System.Data.Entity.DbSet<DemoOrderItem> DemoOrderItems { get; set; } // DEMO_ORDER_ITEMS
        public System.Data.Entity.DbSet<DemoProductInfo> DemoProductInfoes { get; set; } // DEMO_PRODUCT_INFO
        public System.Data.Entity.DbSet<DemoUser> DemoUsers { get; set; } // DEMO_USERS
        public System.Data.Entity.DbSet<Operatore> Operatori { get; set; } // OPERATORE

        static SomministrazioneDbContext()
        {
            System.Data.Entity.Database.SetInitializer<SomministrazioneDbContext>(null);
        }

        public SomministrazioneDbContext()
            : base("Name=SomministrazioneDbContext")
        {
        }

        public SomministrazioneDbContext(string connectionString)
            : base(connectionString)
        {
        }

        public SomministrazioneDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public SomministrazioneDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public SomministrazioneDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public static bool IsSqlParameterNull(Oracle.ManagedDataAccess.Client.OracleParameter param)
        {
            var sqlValue = param.Value;
            var nullableValue = sqlValue as Oracle.ManagedDataAccess.Types.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }
        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new DemoCustomerConfiguration());
            modelBuilder.Configurations.Add(new DemoOrderConfiguration());
            modelBuilder.Configurations.Add(new DemoOrderItemConfiguration());
            modelBuilder.Configurations.Add(new DemoProductInfoConfiguration());
            modelBuilder.Configurations.Add(new DemoUserConfiguration());
            modelBuilder.Configurations.Add(new OperatoreConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new DemoCustomerConfiguration(schema));
            modelBuilder.Configurations.Add(new DemoOrderConfiguration(schema));
            modelBuilder.Configurations.Add(new DemoOrderItemConfiguration(schema));
            modelBuilder.Configurations.Add(new DemoProductInfoConfiguration(schema));
            modelBuilder.Configurations.Add(new DemoUserConfiguration(schema));
            modelBuilder.Configurations.Add(new OperatoreConfiguration(schema));
            return modelBuilder;
        }
    }
}
// </auto-generated>
